language: python
sudo: false
python:
  - "2.7"
cache:
  directories:
  - .cache/pip/
  - $HOME/.cache/pip

install:
- |
  pip install django==$DJANGO_VERSION
  pip install -r requirements.txt --use-mirrors
  python setup.py develop

script: "nosetests -w pyjade/testsuite/ -v"
env:
  matrix:
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
